from sqlalchemy import Column, Integer, String, Date, ARRAY
from sqlalchemy.orm import declarative_base

BASE = declarative_base()

class Games(BASE):
    __tablename__ = 'raw_games'
    AppID = Column(Integer, primary_key=True, nullable=False)
    Name = Column(String(200), nullable=False)
    ReleaseDate = Column(Date, nullable=False)
    EstimatedOwners = Column(String(200), nullable=False)
    PeakCCU = Column(Integer, nullable=False)
    RequiredAge = Column(Integer, nullable=False)
    Price = Column(Integer, nullable=False)
    DLCCount = Column(Integer, nullable=False)
    AboutTheGame = Column(String(500), nullable=True)
    SupportedLanguages = Column(ARRAY(String), nullable=False)
    FullAudioLanguages = Column(ARRAY(String), nullable=False)
    Reviews = Column(String(500), nullable=True)
    HeaderImage = Column(String(500), nullable=False)
    Website = Column(String(500), nullable=True)
    SupportUrl = Column(String(200), nullable=True)
    SupportEmail = Column(String(200), nullable=True)
    Windows = Column(String(15), nullable=False)
    Mac = Column(String(15), nullable=False)
    Linux = Column(String(15), nullable=False)
    MetacriticScore = Column(Integer, nullable=False)
    MetacriticUrl = Column(String(200), nullable=True)
    UserScore = Column(Integer, nullable=False)
    Positive = Column(Integer, nullable=False)
    Negative = Column(Integer, nullable=False)
    ScoreRank = Column(Integer, nullable=True)
    Achievements = Column(Integer, nullable=False)
    Recommendations = Column(Integer, nullable=False)
    Notes = Column(String(500), nullable=True)
    AveragePlaytimeForever = Column(Integer, nullable=False)
    AveragePlaytimeTwoWeeks = Column(Integer, nullable=False)
    MedianPlaytimeForever = Column(Integer, nullable=False)
    MedianPlaytimeTwoWeeks = Column(Integer, nullable=False)
    Developers = Column(String(200), nullable=True)
    Publishers = Column(String(200), nullable=True)
    Categories = Column(String(500), nullable=True)
    Genres = Column(String(500), nullable=True)
    Tags = Column(String(500), nullable=True)
    Screenshots = Column(String(500), nullable=True)
    Movies = Column(String(500), nullable=True)

